
title: Emre_CV
url: 'http://dgmsoft.xyz/'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Emre Aydın
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: emreaydinweb@gmail.com
phone: --------------
website: https://github.com/emreaydinweb #do not add http://
linkedin: emre-aydın
github: emreaydinweb
twitter: '@webjeda'

#Update all the sections by editing the files inside _includes folder.

theme: jekyll-theme-architect
